### ISSUE TITLE
请设置cookies储存原本的信息

### ISSUE THREAD

**Issue by Caishangqi** [Ba1oretto/Minecraft-Server-WebStore#2]
Cookie 并不是它的原意“甜饼”的意思, 而是一个保存在客户机中的简单的文本文件, 这个文件与特定的 [Web](https://baike.baidu.com/item/Web/150564) 文档关联在一起, 保存了该客户机访问这个Web 文档时的信息, 当客户机再次访问这个 Web 文档时这些信息可供该文档使用。由于“Cookie”具有可以保存在客户机上的神奇特性, 因此它可以帮助我们实现记录用户个人信息的功能, 而这一切都不必使用复杂的[CGI](https://baike.baidu.com/item/CGI/607810)等程序[ ]()[2]  。
举例来说, 一个 Web 站点可能会为每一个访问者产生一个唯一的[ID](https://baike.baidu.com/item/ID/91584), 然后以 Cookie 文件的形式保存在每个用户的机器上。如果使用浏览器访问 Web, 会看到所有保存在硬盘上的 Cookie。在这个文件夹里每一个文件都是一个由“名/值”对组成的文本文件,另外还有一个文件保存有所有对应的 Web 站点的信息。在这里的每个 Cookie 文件都是一个简单而又普通的文本文件。透过文件名, 就可以看到是哪个 Web 站点在机器上放置了Cookie(当然站点信息在文件里也有保存)

**Comment by barroit** [comment]
你指的是哪方面的 用户登录？购物车？

**Comment by barroit** [comment]
内容保留 以后有用得到的地再添加
